name: Publish NuGet Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore ./WarhammerCombatMathLibrary/WarhammerCombatMathLibrary.sln

      - name: Build
        run: dotnet build --configuration Release --no-restore ./WarhammerCombatMathLibrary/WarhammerCombatMathLibrary.sln
        
      - name: Run tests
        run: dotnet test ./WarhammerCombatMathLibrary/UnitTests/UnitTests.csproj --no-restore --verbosity normal

      - name: Pack NuGet package
        if: github.event_name == 'push'
        run: dotnet pack --configuration Release --no-build --output ./nupkg ./WarhammerCombatMathLibrary/WarhammerCombatMathLibrary/WarhammerCombatMathLibrary.csproj

      - name: Publish NuGet package
        if: github.event_name == 'push'
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push ./nupkg/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json --skip-duplicate
